resource_types:
  - name: depwatcher
    type: docker-image
    source:
      repository: coredeps/depwatcher

resources:
  - name: source-appdynamic-latest
    type: depwatcher
    check_every: 1h
    source:
      type: appd_agent
      name: appd_agent

jobs:
  - name: create-appd-new-line-story
    serial: true
    public: true
    plan:
      - get: source
        resource: source-appdynamic-latest
        trigger: true
        version: every
      - task: create-tracker-story
        file: tasks/create-new-version-story/create.yml