resource_types:
  - name: depwatcher
    type: docker-image
    source:
      repository: coredeps/depwatcher

resources:
  - name: depwatcher-config
    type: git
    source:
      uri: https://github.com/brayanhenao/concourse-depwatcher-golang.git
      branch: main

  - name: source-appdynamic-latest
    type: depwatcher
    check_every: 1h
    source:
      type: appd_agent
      name: appd_agent

jobs:
  - name: create-appd-new-line-story
    serial: true
    public: true
    plan:
      - get: depwatcher-config
      - get: source
        resource: source-appdynamic-latest
        trigger: true
        version: every
      - task: create-tracker-story
        file: depwatcher-config/tasks/create-new-version-story/create.yml